name: Docker Nightly Image CI
run-name: Build 

on:
  push:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: seceron
          password: erdo007erdo007

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/amd64/v3
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: seceron/transferciniz-routing:v1
